# Generated by Django 2.1.5 on 2019-01-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='name',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
